---
- name: Update apt package cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install common administration packages
  ansible.builtin.apt:
    name:
      - curl
      - wget
      - vim
      - git
      - unzip
      - net-tools
      - dnsutils
      - traceroute
      - ufw
      - qemu-guest-agent
      - python3
      - python3-apt
    state: present

- name: Enable and start QEMU Guest Agent
  ansible.builtin.systemd:
    name: qemu-guest-agent
    enabled: true
    state: started
